repos:
  - repo: local
    hooks:
      - id: nixfmt
        name: nixfmt-rfc-style
        entry: nix run nixpkgs#nixfmt-rfc-style -- --check
        language: system
        files: \.nix$
        pass_filenames: true
        stages: [pre-commit]

      - id: nix-flake-check
        name: nix flake check
        entry: nix flake check --no-build
        language: system
        pass_filenames: false
        stages: [pre-push]
