keys:
  - &host_key age1p8tyygvcz35t3w236sjkgrxkmldnhwqg50j4pdpqlf83wspplawqsq2jx2

creation_rules:
  - path_regex: .secrets/.*\.yaml$
    key_groups:
      - age:
          - *host_key

  - path_regex: .secrets/ssh_host_ed25519_key$
    key_groups:
      - age:
          - *host_key

  - path_regex: hosts/hermes/secrets/.*
    key_groups:
      - age:
          - *host_key